export const SkillItems = [
  {
    title: "Tools & Technologies:",
    items: [
      "Figma",
      "Adobe XD",
      "Adobe Photoshop",
      "Adobe Illustrator",
      "Miro",
      "Balsamiq",
      "Clickup",
      "Notion",
      "Clockify",
      "Slack",
      "Trello",
      "Google Sheets",
      "HTML",
      "CSS",
      "Wordpress",
      "Webflow",
    ],
  },
  {
    title: "Industry knowledges:",
    items: [
      "Design thinking",
      "User research",
      "User interviews",
      "Surveys",
      "Experience maps",
      "Mockups",
      "Interactive prototypes",
      "Usability testing",
      "Wireframes",
      "Customer journey maps",
      "Personas",
      "Empathy maps",
      "User stories",
      "Comparative analysis",
      "Design hand-offs",
      "Design systems",
      "Responsive web design",
      "Panel design",
      "Card sorting",
      "User flows",
      "Information architecture",
      "Micro-interactions",
      "Detailed user flows",
      "Service design",
      "Presentation",
    ],
  },
];
